version: 0.0.0.{build}

clone_depth: 1

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      BUILD_SCRIPT: ./build-amd64-buster.sh
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      BUILD_SCRIPT: ./build-rpi-buster.sh
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      BUILD_SCRIPT: ./build-rpi64-buster.sh

install:
  - sh: 'sudo apt update || true'
  - sh: 'sudo apt install -y qemu binfmt-support qemu-user-static'
  - sh: 'docker run --rm --privileged multiarch/qemu-user-static --reset -p yes'

before_build:
  - sh: 'git submodule update --init --recursive'

build_script:
  - sh: 'sh -c $BUILD_SCRIPT'

after_build:
  - sh: 'appveyor PushArtifact out_*/moonlight-qt_*.deb'
  - sh: 'appveyor PushArtifact out_*/moonlight-qt-dbgsym_*.deb || appveyor PushArtifact out_*/moonlight-qt-dbgsym_*.ddeb'

deploy: off
